apiVersion: 1

deleteDatasources:
  - name: "Prometheus"
  - name: "InfluxDB"

datasources:
  - access: "proxy"
    editable: false
    is_default: true
    name: "Prometheus"
    uid: "6R74VAnVz"
    org_id: 1
    type: "prometheus"
    url: "http://prometheus:9090"
    version: 1
  - access: "proxy"
    database: "opgeth"
    editable: false
    is_default: false
    name: "InfluxDB (op-geth)"
    uid: "4knV40nVb"
    org_id: 1
    type: "influxdb"
    url: "http://influxdb:8086"
    user: $INFLUXDB_READ_USER
    secureJsonData:
      password: $INFLUXDB_READ_USER_PASSWORD
    version: 2
